apiVersion: v2
name: rag-docs
description: A Helm chart for RAG-DOCS - Chat with your documents using AI-powered search
type: application
version: 0.1.2
appVersion: "0.1.2"
dependencies:
  - name: minio
    alias: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled
