{{- if .Values.createbuckets.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.createbuckets.name }}
  labels:
    {{- include "rag-docs.labels" . | nindent 4 }}
    app.kubernetes.io/component: createbuckets
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "rag-docs.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: createbuckets
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: createbuckets
          image: "{{ .Values.createbuckets.image.repository }}:{{ .Values.createbuckets.image.tag }}"
          imagePullPolicy: {{ .Values.createbuckets.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              sleep 10
              mc alias set myminio http://{{ .Values.createbuckets.env.MINIO_SERVER }} {{ .Values.createbuckets.env.MINIO_USER }} {{ .Values.createbuckets.env.MINIO_PASSWORD }}
              mc mb myminio/{{ .Values.createbuckets.env.BUCKET_NAME }} || echo 'Bucket may already exist'
              echo 'Setting up event notification for documents bucket...'
              mc event add -p myminio/{{ .Values.createbuckets.env.BUCKET_NAME }} arn:minio:sqs::EMBEDDER:webhook --event put --suffix .pdf
              mc event add -p myminio/{{ .Values.createbuckets.env.BUCKET_NAME }} arn:minio:sqs::EMBEDDER:webhook --event put --suffix .txt
          env:
            {{- range $key, $value := .Values.createbuckets.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.createbuckets.resources | nindent 12 }}
{{- end }}
