{{- if .Values.embedder.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.embedder.name }}
  labels:
    {{- include "rag-docs.labels" . | nindent 4 }}
    app.kubernetes.io/component: embedder
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.embedder.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.embedder.service.type }}
  ports:
    - port: {{ .Values.embedder.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rag-docs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: embedder
{{- end }}
